#pragma once
/// @brief 旧的 Foley 式音效类型
/// @see FoleyType
namespace LowerSoundType
{
	/// @deprecated 请改用 FoleyType::FoleyType
	enum LowerSoundType
	{
		GainSun,
		PeaHit,
		LawnMower,
		PeaShoot1,
		PeaShoot2,
		Chomp1,
		Chomp2,
		PlacePlant,
		ShovelPlant,
		ClickCard,
		CancelCard,
		ZombieShout1,
		ZombieShout2,
		ZombieShout3,
		JackintheboxBGM, //continuous
		GainDiamond,
		ZomboinStart,
		Thunder,
		Decelerate,
		SnorkedDive,
		PlaceBowling,
		ZombieChomp,
		BalloonBurst,
		ZomboinExplode,
		SnorkedEat,
		MenuPluckFlower,
		PogoJump,
		PlanternEnter,
		ZombieFall,
		PuffAttack,
		FumeAttack,
		GainCoin,
		ZombieHit,
		DiggerDig1,
		JackintheboxAh,
		BreakVase,
		PoolCleaner,
		CastBasketball,
		FirePeaHit,
		PeaIgnite,
		ZombossEnter,
		SquashUnn,
		MagnetAttract,
		ButterHit,
		BungeeFall,
		MachineExplode,
		IronAccessoryHit,
		HammerMiss,
		HammerHit,
		Rain,
		DolphinJump,
		DolphinEnter,
		ZombieEnterWater1,
		ZombieEnterWater2,
		BusterGnaw,
		CherryExplode,
		JalapenoExplode,
		ExplodeBefore,
		ConeheadHit,
		Win, //BGM
		BalloonEnter,
		ChomperChomp,
		MelonHit,
		Grow,
		CannonReady,
		Juice, //WDYM?
		NewspaperAngry,
		NewspaperDestroyed,
		Hypnotize,
		MineReady,
		GargantuarRoar,
		GardenPlantGlow,
		EatGarlic,
		PeaShoot,
		TargetFall,
		PickUpShovel,
		CannonLaunch,
		Watering,
		PoleVaulting,
		DiggerDig2,
		DiggerDig3,
		Fertilize,
		PortalClose,
		CoffeeBeanVanish,
		Spray,
		Noooooo,
		ReceiveLetter,
		GoldDrop,
		CastImp,
		ZombossPlaceZombie,
		ZombossStickHead,
		GargantuarDie,
		UnknownHit, //WDYM?
		ZombossBall,
		DiamondDrop,
		DaveRererele,
		DaveRebrerebla,
		DaveWabiwo,
		DaveCauseImCrazyAh,
		Phonograph,
		DancingMusic,
		DaveHaveARoll,
		DaveWawarowaro,
	};

	extern const char* ToString(LowerSoundType sound);

}